#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BarcodeScannerExample.Droid.Resource", IsApplication=true)]

namespace BarcodeScannerExample.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int backgroundColor = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorAccent = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimary = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryDark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int greyColor = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ic_launcher_background = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int scanbotRed = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int sheetColor = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int titleSeparatorColor = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int сolorWarningBackground = 2130771977;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int fab_margin = 2130837504;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int container_bg = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ic_broken_image_white_24dp = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int warning_shape = 2130903042;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int appBarLayout = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int apply = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int barcodeFormat = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int barcode_camerax_demo = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int barcode_scanner_view_demo = 2130968580;
			
			// aapt resource value: 0x7F040007
			public const int barcode_types_list = 2130968583;
			
			// aapt resource value: 0x7F040005
			public const int barcode_type_checker = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int barcode_type_name = 2130968582;
			
			// aapt resource value: 0x7F040008
			public const int batch_rtu_ui = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int camera = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int camerax = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int clear_storage = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int container = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int description = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int docFormat = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int docText = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int finder_overlay = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int flash = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int image = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int imageContainer = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int license_info = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int linearLayout = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int recognisedItems = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int result = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int rtu_ui = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int rtu_ui_aroverlay = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int rtu_ui_image = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int rtu_ui_import = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int settings = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int snapImage = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int snapped_message = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int textView = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int toolbar = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int warning_shape = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int warning_view = 2130968610;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_main = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int barcode_camerax_activity = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int barcode_item = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int barcode_result = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int barcode_scanner_view_activity = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int barcode_type = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int barcode_types = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int detailed_item_data = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int snap_image_item = 2131034120;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int Icon = 2131099648;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int action_settings = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int app_name = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppTheme = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int BottomSheetMenuItem = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int NegativeButtonStyle = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int PositiveButtonStyle = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int Scanbot_Demo_ActionBar = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int Scanbot_Demo_ActionBarThemeOverlay = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int Scanbot_Demo_Dialog = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int Scanbot_Demo_Dialog_Title = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int Scanbot_Demo_MaterialTwoButtonTeaser_Button = 2131230728;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
